### ISSUE TITLE
I'm trained in CelebAMask-HQ dataset, the result of best iou is 22.88%,Using the same code and dataset,Why get the big differerce result. 

### ISSUE THREAD

**Issue by Danbinabo** [JACKYLUO1991/FaceParsing#12]

**Comment by JACKYLUO1991** [comment]
@Danbinabo Even with a resolution of 256, such low results cannot be achieved. I don’t know if you have modified the script, so I don’t know where the problem is. Someone has reproduced the results, at least over 70% on IoU.

**Comment by Danbinabo** [comment]
Can you provide the model?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jacky LUO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 晚上8:57
收件人:&nbsp;"JACKYLUO1991/FaceParsing"<FaceParsing@noreply.github.com&gt;;
抄送:&nbsp;"丹兵"<994329541@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JACKYLUO1991/FaceParsing] I'm trained in CelebAMask-HQ dataset, the result of best iou is 22.88%,Using the same code and dataset,Why get the big differerce result.  (#12)





 
@Danbinabo Even with a resolution of 256, such low results cannot be achieved. I don’t know if you have modified the script, so I don’t know where the problem is. Someone has reproduced the results, at least over 70% on IoU.
