### ISSUE TITLE
How to test on image

### ISSUE THREAD

**Issue by myounus96** [JACKYLUO1991/FaceParsing#13]

**Comment by JACKYLUO1991** [comment]
@myounus96 You should first configure the relevant parameters in parameters.py, and then run the main.py script. Of course, first you need to train the model...

**Comment by myounus96** [comment]
> @myounus96 You should first configure the relevant parameters in parameters.py, and then run the main.py script. Of course, first you need to train the model...

Have done that..tester.py only producing accuracy metrics..not coloured masked predicted images..

**Comment by JACKYLUO1991** [comment]
@myounus96 Please refer to the detection.py script in the deployment folder.

**Comment by myounus96** [comment]
it just keep giving 'load NONE from pretrained checkpoint' error.

**Comment by JACKYLUO1991** [comment]
@myounus96 

You should load face detect box weight from （https://pan.baidu.com/s/14MzwqOBxY2tciC5V8MXW2w and password is a9ty）first.

**Comment by myounus96** [comment]
> @myounus96
> 
> You should load face detect box weight from （https://pan.baidu.com/s/14MzwqOBxY2tciC5V8MXW2w and password is a9ty）first.

Thank you will try this.

**Comment by myounus96** [comment]
I got 'page doesn't exist'.
![image](https://user-images.githubusercontent.com/13608139/92731255-48c50b00-f38e-11ea-9258-79655f904eba.png)

**Comment by JACKYLUO1991** [comment]
@myounus96 Please check your email.

**Comment by myounus96** [comment]
@JACKYLUO1991 didn't receive any email yet, will confirm when received.

**Comment by myounus96** [comment]
Got the email.

**Comment by JACKYLUO1991** [comment]
@ success or failure?

**Comment by myounus96** [comment]
> @ success or failure?

Getting this error `FileNotFoundError: [Errno 2] No such file or directory: './segmentation/ParseNet_120_G.pth'`.
By placing trained model in segmentation folder, getting this `size mismatch for classifier2.weight: copying a param with shape torch.Size([19, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 384, 1, 1]).`.
@JACKYLUO1991

**Comment by JACKYLUO1991** [comment]
@myounus96 You need to train the segmentation network first. What you were given before is the weight of face detection.

**Comment by myounus96** [comment]
> > @myounus96 You should first configure the relevant parameters in parameters.py, and then run the main.py script. Of course, first you need to train the model...
> 
> Have done that..tester.py only producing accuracy metrics..not coloured masked predicted images..

Already done that, have mentioned in my 2nd comment. ^

**Comment by JACKYLUO1991** [comment]
@myounus96 I think line 390 of the detection.py script is what you need.
