### ISSUE TITLE
the detection box  url is canceled...

### ISSUE THREAD

**Issue by Chic-J** [JACKYLUO1991/FaceParsing#16]
Thanks for ur code base.Me and my group are about to reproduce your model, can u leave me a new url for the detection box？

**Comment by JACKYLUO1991** [comment]
@Chic-J Please visit: https://pan.baidu.com/s/1vgYnw89M7ALqSfD52MIc3w Password: 6ize

**Comment by Chic-J** [comment]
Thanks. And I read the code.Much I’ve learned!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: JackyLUO1991<mailto:notifications@github.com>
发送时间: 2020年10月17日 9:40
收件人: JACKYLUO1991/FaceParsing<mailto:FaceParsing@noreply.github.com>
抄送: chongjin chen<mailto:lazyyyyeah@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [JACKYLUO1991/FaceParsing] the detection box url is canceled... (#16)


@Chic-J<https://github.com/Chic-J> Please visit: https://pan.baidu.com/s/1vgYnw89M7ALqSfD52MIc3w Password: 6ize

―

**Comment by JACKYLUO1991** [comment]
@Chic-J Thank you for your interest in our work.

**Comment by Chic-J** [comment]
I found an error when training the model.  How to solve?
