### ISSUE TITLE
invalid value when training

### ISSUE THREAD

**Issue by Chic-J** [JACKYLUO1991/FaceParsing#17]
![M3K$@1EEVOAV8`{JA_F1R4T](https://user-images.githubusercontent.com/41068484/96837088-72d31800-1478-11eb-9bff-b9ad071f51a4.png)

i wonder what causes this problem?
besides，i wonder why  the loss is so small? i train the model and the loss became 4.3e-0.5 using the FaceParseNet18 or EHANet18?

**Comment by Chic-J** [comment]
solved.but a new error comes up.
![Uploading image.png…]()

**Comment by JACKYLUO1991** [comment]
@Chic-J Sorry, your picture doesn't appear on the page.

**Comment by Chic-J** [comment]
> @Chic-J Sorry, your picture doesn't appear on the page.

All done. but I still can fine the output image of the tesing.where do you put them in?and how can i test my own photo？should i need to take a photo and make labels of it?

**Comment by Chic-J** [comment]
> @Chic-J Sorry, your picture doesn't appear on the page.

All done. but I wonder where do you put the output images of the testing?and how can I test on my own photo?should i take one and make labels of it ?

**Comment by Chic-J** [comment]
and  the epoch is 10.but the result is 10 .pth file...this means the 9th file is the final result?

**Comment by JACKYLUO1991** [comment]
@Chic-J For testing, please refer to the script in the deployment folder.

**Comment by Chic-J** [comment]
> @Chic-J For testing, please refer to the script in the deployment folder.

OK will try it

**Comment by Chic-J** [comment]
I found a warning.When i choose EHANet18 mode in detection.py and run it, a fault occurs.but good with FaceParseNet18.
![image](https://user-images.githubusercontent.com/41068484/97110161-9c0ed500-1712-11eb-927a-c16506c36651.png)

**Comment by Chic-J** [comment]
solved.
