### ISSUE TITLE
Is there anyone run this code up without issue?

### ISSUE THREAD

**Issue by WindQingYang** [JACKYLUO1991/FaceParsing#3]
Is there anyone run this code up without issue?

**Comment by JACKYLUO1991** [comment]
@WindQingYang What is the problem?

**Comment by WindQingYang** [comment]
> @WindQingYang What is the problem?

Confirm this code is workable or not, since no one comments, I want to apply it to my face anti-spoofing research.
If use, I will cite.

**Comment by JACKYLUO1991** [comment]
@WindQingYang Certainly available, you can contact me if you have any questions. If it does n’t work, it ’s academic fraud and can criticize me.
