### ISSUE TITLE
I can not search out the paper "EHANet: An effective hierarchical aggregation network for face parsing"

### ISSUE THREAD

**Issue by HulkMaker** [JACKYLUO1991/FaceParsing#6]
what is the link of the your work's paper: EHANet: An effective hierarchical aggregation network for face parsing ?
I can not search it out.

**Comment by JACKYLUO1991** [comment]
@HulkMaker The paper is in the editorial decision and will be published in the next few days after acceptance. Thank you for your support for our work.

**Comment by JACKYLUO1991** [comment]
@HulkMaker Hi, the paper is available.
