### ISSUE TITLE
Since this paper is accepted, can you release more details? Such as pretrained model, datasets, requirements, and procedures.

### ISSUE THREAD

**Issue by leonmakise** [JACKYLUO1991/FaceParsing#8]
Please tell us more details, such as pretrained model, datasets, requirements, and procedures.

**Comment by JACKYLUO1991** [comment]
@leonmakise After the internship group agrees, I will upload it immediately.

**Comment by wy3406** [comment]
@JACKYLUO1991 
Thank you for your research work
 Can you upload the trained tensorboard as our training reference?

**Comment by GeneralJing** [comment]
这么久了，大佬还不可以提供模型吗
