### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by ash368** [JACKYLUO1991/FaceParsing#9]
`File "/content/FaceParsing/trainer.py", line 100, in train
    c_loss = cross_entropy2d(labels_predict, labels.long(), reduction='mean')
  File "/content/FaceParsing/criterion.py", line 13, in cross_entropy2d
    n, c, h, w = input.size()
AttributeError: 'list' object has no attribute 'size'`

i'm getting this error while training

**Comment by leonmakise** [comment]
I got the same error as yours.

**Comment by JACKYLUO1991** [comment]
@leonmakise @ash368 I guess it is caused by changing the loss function, EHANet has three outputs, so if you modify the loss function to cross-entropy, please modify the output of the network, for example, modify [[seg1, seg2], [edge]] to seg1 in ehanet.py.

**Comment by leonmakise** [comment]
@JACKYLUO1991 It works. Thanks a lot!
